name: hexo_auto_push
on: 
  push: 
    branches: 
      - hexo
jobs:
  hexo_auto_push:
    runs-on: ubuntu-latest
    steps:
      - name: Download Necessary Files
        uses: actions/checkout@v2
        with:
          ref: 'hexo'
          path: 'zizhaolaisuimuqu.github.io'
      - name: Install Nodejs
        uses: actions/setup-node@v2
        with: 
          node-version: '14'
      - name: Install Hexo
        run: |
          npm install hexo-cli -g
      - name: Cache Dependencies
        id: cacha-dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: |
          npm install
      - name: Clean Hexo Page
        run: |
          hexo clean
      - name: Generate Hexo Page
        run: |
          hexo generate
      - name: Setup Deploy Key
        env: 
          DEPLOY_KEY: ${{ secrets.TITLE }}
        run: |
          mkdir -p ~/.ssh./
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Setup Git Infomation
        run: |
           git config --global user.name ''
           git config --global user.email ''
      - name: Deploy Hexo Page
        run: |
          hexo deploy